### ISSUE TITLE
Receive GM-only replies from GPT

### ISSUE THREAD

**Issue by DrDoomDEU** [vizovitin/foundryvtt-ask-chatgpt#8]
Hi there,

it would be great if  the reply from GPT would be visible only to the GM with an option to then show it to all players.

In this way I could first prequalify the answer.

I have seen this as a default setting in another AI module so I guess it is feasible.

Thanks for the great work!

**Comment by vizovitin** [comment]
You could just ask GPT via `/w gpt <message>` instead of `/? <message>` and then right click on the result and select "Reveal To Everyone".

Closing this. Feel free to reopen if this doesn't work for you for some reason.
